[resolve #14] creation of the services implementation
eamquindio/practicas_frontend_web pull request #48
Opened 2019-10-21 21:05 UTC by ndavila1

2019-10-24 18:36 UTC, ingesofteam commented on src/app/services/peticiones.service.ts
> +@Injectable({
tambien se deben poder enviar los headers...

2019-10-26 13:32 UTC, Daryl110 requested changes

2019-10-26 13:32 UTC, Daryl110 commented on src/app/app.module.ts
> +
un espacio de mas

2019-10-26 13:32 UTC, Daryl110 commented on src/app/services/peticiones.service.ts
> +
un espacio de mas

2019-10-26 13:35 UTC, Alvaro1050 commented on src/app/app.module.ts
> +
un espacio de mas

2019-10-26 13:35 UTC, Alvaro1050 commented on src/app/services/peticiones.service.ts
> +
un espacio de mas

2019-10-26 13:35 UTC, Alvaro1050 approved these changes

2019-10-26 13:36 UTC, jhonquirama approved these changes

2019-10-26 13:36 UTC, Daryl110 approved these changes

2019-10-31 11:53 UTC, merged